AuthWithPasswordInput:
    type: relay-mutation-input
    description: "For authentification with email and password."
    config:
        fields:
            email:
                description: "A registered email address"
                type: "String!"
            password:
                description: "The plaintext password belonging to the account."
                type: "String!"

AuthWithPasswordPayload:
    type: relay-mutation-payload
    description: "Authentification answer to fetch apiKey."
    config:
        fields:
            apiKey:
                description: "A generated key to use in header to access protected fields."
                type: "String!"
            expiresAt:
                description: "Datetime when the key expires."
                type: "String"