Character:
  type: object
  inherits: [Fighter]
  config:
    interfaces: [Fighter]
    description: "A character in this realm."
    fields:
      name: {type: "String!", description: "Unique name of the character without colour information."}
      stats: {type: "[CharacterStat!]", description: "Character details"}