# Configuration
Configuration:
    type: object
    config:
        description: "Realm configuration."
        fields:
            core:
                type: "Library!"
                description: "Configuration of the LotGD core."
            crate:
                type: "Library!"
                description: "Configuration of the crate around the core."
            modules:
                type: "[Library]"
                description: "Details about the modules installed on this realm."
