Library:
    type: object
    config:
        description: "A library, or piece of software."
        fields:
            name:
                type: "String!"
                description: "Name of this library."
            version:
                type: "String!"
                description: "Version number, conforming to semantic versioning."
            library:
                type: "String!"
                description: "Technical name of this library, in vendor/package format."
            url:
                type: "String"
                description: "Access URL of the library, i.e., location of its code."
            author:
                type: "String"
                description: "Author, or list of authors, of this library."
