Query:
    type: object
    config:
        description: "The GraphQL interface for communicating with the LotGD core."
        fields:
            Realm:
                description: "General information about the server configuration."
                type: "Realm"
                resolve: "@=resolver('realm_realm')"
