# This is the type that will be the root of our query, and the
# entry point into our schema. It gives us the ability to fetch
# objects by their IDs, as well as to fetch the undisputed hero
# of the Star Wars trilogy, R2-D2, directly.
# This is the type that will be the root of our query, and the
# entry point into our schema.
#
# This implements the following type system shorthand:
#   type Query {
#     hero(episode: Episode): Character
#     human(id: String!): Human
#     droid(id: String!): Droid
#     rebels: Faction
#     empire: Faction
#     node(id: String!): Node
#   }
#
Query:
    type: object
    config:
        description: "The GraphQL interface for communicating with the lotgd core."
        fields:
            Realm:
                type: "Realm"
                resolve: "@=resolver('realm_realm')"