Realm:
    type: object
    config:
        description: "Common information about the Realm."
        fields:
            url:
                type: "String"
                description: "URL of this realm."
            name:
                type: "String!"
                description: "The name of this realm."
            description:
                type: "String"
                description: "The description of this realm."
            configuration:
                type: "Configuration!"
                description: "Information about the configuration of htis realm."
