# Notice about creation of types:
#   for array return valies in the Resolver, use object.
#   If the type is interface, it needs a resolveType argument to resolve the real type.
Realm:
    type: object
    config:
        description: "Common informations about the Realm"
        fields:
            name:
                type: "String"
                description: "The name of this realm."
            crateVersion:
                type: "String"
                description: "The version of LotGD\\Crate\\WWW"
            coreVersion:
                type: "String"
                description: "The version of LotGD\\Core"
#        resolveType: "@=resolver('realm_type', [value])"