Session:
    type: object
    config:
        description: "Information about the current session."
        fields:
            authToken:
                type: "String"
                description: "Authentification Token to this realm."
            expiresAt:
                type: "String"
                description: "Date this session expires at."
            user:
                type: "User"
                description: "The user account associated with this session."