User:
    type: object
    config:
        description: "A user account."
        fields:
            id:
                type: "ID!"
                description: "Unique ID of the user."
            name:
                type: "String!"
                description: "Name of the user library."
            characters:
                type: "[Character]!"
                description: "Characters belonging to this user."
