#lotgd_create_php:
#    resource: "@AppBundle/Controller/GraphController.php"
#    type: annotation
#    prefix: /
#lotgd_create_php_graphiql:
#    resource: "@AppBundle/Controller/GraphiQLController.php"
#    type: annotation
#    prefix: /graphiql
#overblog_graphql_endpoint:
#    path: /
#    defaults:
#        _controller: LotGD:Crate:WWW:AppBundle:Controller:GraphController:endpoint

overblog_graphql_endpoint:
  path: /
  defaults:
    _controller: lotgd.controller.graphql:endpointAction
    _format: "json"

#overblog_graphql_endpoint:
#    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
overblog_graphql_graphiql:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphiql.yml"