# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        auth:
            id: lotgd.user_provider
        endpoint:
            id: lotgd.api_key_provider
        
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        auth:
            pattern: ^/auth
            anonymous: ~
            stateless: true
            guard:
                authenticators:
                    - lotgd.credential_authenticator
            provider: auth

        endpoint:
            pattern: ^/
            anonymous: ~
            stateless: true  
            simple_preauth:
                authenticator: lotgd.token_authenticator
            provider: endpoint
  
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
