# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Core service
    lotgd.core.game:
        class: LotGD\Crate\GraphQL\Services\CoreGameService
        public: true
    # Manager services
    lotgd.crate.graphql.user_manager:
        class: LotGD\Crate\GraphQL\Services\UserManagerService
        public: true
        calls:
            - [setCoreGameService, ["@lotgd.core.game"]]
    lotgd.crate.graphql.character_manager:
        class: LotGD\Crate\GraphQL\Services\CharacterManagerService
        public: true
        calls:
            - [setCoreGameService, ["@lotgd.core.game"]]

    # User providers
    lotgd.api_key_provider:
        class: LotGD\Crate\GraphQL\AppBundle\Security\ApiKeyProvider
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]

    # Authenticators
    lotgd.token_authenticator:
        class: LotGD\Crate\GraphQL\AppBundle\Security\TokenAuthenticator
        public: true

    # Authorizations
    lotgd.authorization:
        class: LotGD\Crate\GraphQL\Services\AuthorizationService
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]

    # Events
    lotgd.listeners.authentificationFailure:
        class: LotGD\Crate\GraphQL\SymfonyEventListeners\AuthentificationFailureListener
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Controllers
    lotgd.controller.graphql:
        class: LotGD\Crate\GraphQL\AppBundle\Controller\GraphController
        public: true
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            - "@overblog_graphql.request_batch_parser"
            - "@overblog_graphql.request_executor"
            - "@overblog_graphql.request_parser"
            - "%overblog_graphql.handle_cors%"
            - "%overblog_graphql.batching_method%"
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
