# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    lotgd.core.game:
        class: LotGD\Crate\GraphQL\AppBundle\Services\CoreGameService
    # User providers
    lotgd.user_provider:
        class: LotGD\Crate\GraphQL\AppBundle\Security\UserProvider
    lotgd.api_key_provider:
        class: LotGD\Crate\GraphQL\AppBundle\Security\ApiKeyProvider
    # Authenticators
    lotgd.credential_authenticator:
        class: LotGD\Crate\GraphQL\AppBundle\Security\CredentialAuthenticator
        calls:
            - [setContainer, ["@service_container"]]
    lotgd.token_authenticator:
        class: LotGD\Crate\GraphQL\AppBundle\Security\TokenAuthenticator
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
