# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Core service
    lotgd.core.game:
        class: LotGD\Crate\GraphQL\Services\CoreGameService
    # Manager services
    lotgd.crate.graphql.user_manager:
        class: LotGD\Crate\GraphQL\Services\UserManagerService
        calls:
            - [setCoreGameService, ["@lotgd.core.game"]]
    lotgd.crate.graphql.character_manager:
        class: LotGD\Crate\GraphQL\Services\CharacterManagerService
        calls:
            - [setCoreGameService, ["@lotgd.core.game"]]

    # User providers
    lotgd.api_key_provider:
        class: LotGD\Crate\GraphQL\AppBundle\Security\ApiKeyProvider
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
    # Authenticators
    lotgd.token_authenticator:
        class: LotGD\Crate\GraphQL\AppBundle\Security\TokenAuthenticator

    # Events
    lotgd.listeners.authentificationFailure:
        class: LotGD\Crate\GraphQL\SymfonyEventListeners\AuthentificationFailureListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
