CreatePasswordUserInput:
    type: relay-mutation-input
    description: "Information needed to create an user which authentifications himself with email/password."
    config:
        fields:
            name:
                description: "The user's name."
                type: "String!"
            email:
                description: "The user's email address."
                type: "String!"
            password:
                description: "The plaintext password."
                type: "String!"

CreatePasswordUserPayload:
    type: relay-mutation-payload
    description: "Payload to access information for a freshly created user."
    config:
        fields: