services:
    app.graph.resolver.realm:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Resolver\RealmResolver
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.resolver, alias: "realm_resolver", method: "resolve" }

    app.graph.resolver.session:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Resolver\SessionResolver
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.resolver, alias: "session_resolver", method: "resolve" }

    app.graph.resolver.user:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Resolver\UserResolver
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.resolver, alias: "user_resolver", method: "resolve" }

    app.graph.resolver.viewpoint:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Resolver\ViewpointResolver
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.resolver, alias: "viewpoint_resolver", method: "resolve" }

    app.graph.resolver.fighter:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQ\Resolver\FighterResolver
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.resolver, alias: "type_resolver", method: "resolveType" }


    app.graph.resolver.character:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Resolver\CharacterResolver
        public: true
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.resolver, alias: "character_resolver", method: "resolve" }
            - { name: overblog_graphql.resolver, alias: "character_stat_resolver", method: "resolveCharacterStat" }