services:
    lotgd.crate.graph.mutation.auth:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Mutation\AuthMutation
        tags:
            - { name: overblog_graphql.mutation, alias: "auth_with_password", method: "authWithPassword" }
            - { name: overblog_graphql.mutation, alias: "create_password_user", method: "createPasswordUser" }
    lotgd.crate.graph.mutation.viewpoint:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Mutation\ViewpointMutation
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.mutation, alias: "take_action", method: "takeAction" }
    lotgd.crate.graph.mutation.character:
        class: LotGD\Crate\GraphQL\AppBundle\GraphQL\Mutation\CharacterMutation
        calls:
            - [setContainer, ["@service_container"]]
            - [setCoreGameService, ["@lotgd.core.game"]]
        tags:
            - { name: overblog_graphql.mutation, alias: "create_character", method: "createCharacter" }
